FROM apache/airflow:2.8.0

USER root
# Install system-level GIS dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gdal-bin \
    libgdal-dev \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
# Install Python libraries
RUN pip install --no-cache-dir \
    rasterio==1.3.9 \
    shapely==2.0.2 \
    boto3 \
    psycopg2-binary \
    python-dotenv